# -*- coding: utf-8 -*-
"""langGraph-Practice-agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t-SJn5Z5sQ-EPYwJf_fw7bC_wPfmQece
"""

s = "jadhfkljakasvd"
count=0
for char in s:
  if char in ['a','e','i','o','u']:
    count+=1
print(count)

s = "asfajdgfkjdbfu"
seen=set()
duplicate=set()
for i in s:
  if i in seen:
    duplicate.add(i)
  else:
    seen.add(i)
print(duplicate)

s="detartrated"
if s[::-1]==s:
  print('True')
else:
  print('False')

nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
ans=0
for num in nums:
  if num%2==0:
    ans = ans+num
print(ans)

nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

nums=nums[1::2]



print(nums)

name = input("Enter your name: ")
print(f"Good afternoon {name}")

Name = input("Enter your name:")
Date = input("Enter the Date")
print(f"Dear {Name}, You are selected! {Date}")

str = "manoj  kumar"
if str.count(" ")==2:
  print("Double space detected")
else:
  print("Double space not detected")
print(str.capitalize())
print(str.find("  "))
print(str.replace("  ","--"))

lmarks=[]
for i in range(6):
  marks = int(input(f"Enter the marks of the student {i+1}: "))
  lmarks.append(marks)
print(lmarks)

#list -- mutable
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
nums=nums[::2]
sum=0
for i in nums:
  sum =sum+i
print(sum)
nums[3] = 5
print(nums)



#tuple -- immutable
a = (7, 0, 8, 0, 0, 9)
count=0
for i in a:
  if i==0:
    count+=1

print(count)
a[3] = 5
print(a)

#ditionary -- mutable
a = {
"key": "value",
"harry": "code",
"marks": "100",
"list": [1, 2, 9]
}
print(a)
a["harry"]="potter"
print(a)
print(a.items())
print(a.get("marks"))
print(a["marks"])

#set -- mutable
s = {1,8,2,3}
print(s)

nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
nums[4]=56
nums.append("sa")
print(nums)

s = set()
s.add(20)
s.add(20.0)
s.add('20')
print(s)
print(len(s))
print(type(s))

s = {8, 7, 12, "Harry",(1,2)}
l = list(s)
s.remove(12)
s.add(4)
print(s)

n = 11
for i in range(n):
  line=""
  for j in range(n-2*i):
    line = line + "*"
  print(line)

l = ["Harry", "Soham", "Sachin", "Rahul"]
name=[]
for i in l:
  if i[0]=='S' or i[0]=='s':
    name.append(i)
print(name)

l = ["Harry", "Soham", "Sachin", "Rahul"]
name=[]
for i in l:
  if i[0].upper()=='S':
    name.append(i)
print(name)

def add_item(item, lst=[]):
    lst.append(item)
    return lst

print(add_item(1))
print(add_item(2))
print(add_item(3))

#Write a program to find whether a given number is prime or not
num = int(input("Enter a number: "))

if num <= 1:
    print("Not a prime number")
else:
    for i in range(2, int(num**0.5)):
       if num % i == 0:
            print("Not a prime number")
            break
    else:
        print("Prime number")

#Write a program to calculate the factorial of a given number using for loop
num = int(input("Enter a number: "))
factorial=1
for i in range(2,num+1):
  factorial = factorial*i
print(factorial)

#Write a program to print multiplication table of n using for loops in reversed order
num = int(input("Enter a number: "))
for i in range(10, 0, -1):
  print(f"{num} x {i} = {num*i}")

for i in range(n):
  print(" " * (n - i) + "*" * (2*i - 1))

def greet(name = "Sarthak"):
  print(f"Say Hello to {name}")
greet("manoj")

import re
p = "*(&(*^&*%manohar parikar zindabad))"
p_ = re.sub(r'[*()^&%]','',p)
print(p_)

p = " great "
print(p)
print(p.strip())

p="savitri\n"
q="manorama\n"
r="kirmanda"
print(p,q)
print(q.strip(),r)

nums = [2,3,4,5]
square = list(map(lambda x:x*x, nums))
print(square)

from typing import Dict,TypedDict,List
from langgraph.graph import StateGraph,START,END
import math

class AgentState(TypedDict):
  message : str

def greeting_node(state: AgentState) -> AgentState:
  """A simple node that adds the greeting message in its state"""
  state["message"] = "hi " + state["message"] + " how are you doing"

  return state
graph = StateGraph(AgentState)
graph.add_node("greeter",greeting_node)

graph.set_entry_point("greeter")
graph.set_finish_point("greeter")

app = graph.compile()
result = app.invoke({"message": "Sarthak"})
result["message"]

class AgentState(TypedDict):
  values: List[int]
  name: str
  result: str

def process_val(state:AgentState)->AgentState:
  """This function is used to sum the values in the state and add them into it"""
  state["result"] = f"hi {state["name"]} your total sum is {sum(state["values"])}"
  return state

graph = StateGraph(AgentState)
graph.add_node("processor",process_val)

graph.set_entry_point("processor")
graph.set_finish_point("processor")
app = graph.compile()
answer = app.invoke({"values": [1,2,3,4,5], "name": "Sarthak"})
print(answer["result"])

class AgentState(TypedDict):
  list: List[int]
  name: str
  operation:str
  result:str

def process_val(state: AgentState)->AgentState:
  """A funtion that either do multiplication and addition based on the operation provided in the state"""
  state["result"] = f"hi {state["name"]} based on your provided operation {state["operation"]} the result is {math.prod(state["list"]) if state["operation"]=="*" else sum(state["list"])}"
  return state

graph = StateGraph(AgentState)
graph.add_node("processor",process_val)

graph.set_entry_point("processor")
graph.set_finish_point("processor")
app = graph.compile()
answer = app.invoke({"list": [1,2,3,4,5], "name": "Sarthak","operation" :"+"})
print(answer["result"])

class AgentState(TypedDict):
  name:str
  age:int
  skill:List[int]
  result:str

def Greeting(state:AgentState)->AgentState:
  """Asking about person's age and add this to state """
  state["result"] =f"{state["name"]} welcome to the system"
  return state
def Age(state:AgentState)->AgentState:
  """Asking about person's age and add this to state """
  state["result"] = state["result"] + f"you are {state["age"]} years old "
  return state
def Skill(state:AgentState)->AgentState:
  """Asking about person's age and add this to state """
  state["result"] = state["result"] +  f" you have skills in {", ".join(state["skill"][:-1]) + " and " + state["skill"][-1]}"
  return state

graph = StateGraph(AgentState)
graph.add_node("Hello",Greeting)
graph.add_node("Age",Age)
graph.add_node("Skill",Skill)
graph.add_edge("Hello","Age")
graph.add_edge("Age","Skill")
graph.set_entry_point("Hello")
graph.set_finish_point("Skill")
app = graph.compile()
answer = app.invoke({"name":"Linda","age":31,"skill":["Machine Learning","Python","LangGraph"]})
print(answer["result"])

class AgenState(TypedDict):
  number1:int
  operation1:str
  number2:int
  number3:int
  number4:int
  operation2:str
  finalNumber1:int
  finalNumber2:int

def adder(state:AgenState)->AgenState:
  """This is for adding"""
  state["finalNumber1"] = state["number1"] + state["number2"]
  return state

def adder2(state:AgenState)->AgenState:
  """This is for adding"""
  state["finalNumber2"] = state["number3"] + state["number4"]
  return state
def substracter(state:AgenState)->AgenState:
  """This is for substracting"""
  state["finalNumber1"] = state["number1"] - state["number2"]
  return state

def substracter2(state:AgenState)->AgenState:
  """This is for substracting"""
  state["finalNumber2"] = state["number3"] - state["number4"]
  return state

def decider(state:AgenState)->AgenState:
  """This is a conditional node between adding or substracting"""
  if state["operation1"] == "+":
    return "additional_operation"

  elif state["operation1"] == "-":
    return "substraction_operation"

def decider2(state:AgenState)->AgenState:
  """This is a conditional node between adding or substracting"""
  if state["operation2"] == "+":

    return "additional_operation2"

  elif state["operation2"] == "-":
    return "substraction_operation2"
graph = StateGraph(AgenState)

graph.add_node("adder",adder)
graph.add_node("substracter",substracter)
graph.add_node("decider",decider)
graph.add_node("router",lambda state:state)
graph.add_edge(START,"router")

graph.add_conditional_edges(
    "router",
    decider,
    {
        "substraction_operation" : "substracter",
        "additional_operation" : "adder"
    }
)
graph.add_node("router2",lambda state:state)
graph.add_node("substracter2",substracter2)
graph.add_node("adder2",adder2)
graph.add_edge("adder","router2")
graph.add_edge("substracter","router2")
graph.add_conditional_edges(
    "router2",
    decider2,
    {
        "substraction_operation2" : "substracter2",
        "additional_operation2" : "adder2"
    }
)

graph.add_edge("adder2", END)
graph.add_edge("substracter2", END)
app = graph.compile()
initial_state = AgentState(number1 = 10, operation1="-", number2 = 5, number3 = 7, number4=2, operation2="+", finalNumber1= 0, finalNumber2 = 0)
answer = app.invoke(initial_state)
print(answer["finalNumber1"])
print(answer["finalNumber2"])

